language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
- pip install bandit flake8 pep8-naming
script:
- bandit -r .
- flake8 .
- pytest
deploy:
  provider: pypi
  user: drewpearce
  password:
    secure: "pm/zMeBk29x+e+/6Gjy5cvnMmpucwNoyBAyP+fMYwLcqBQWqVyChccfi2asuk2N7tVIuPnctDBCOFiPc86FyiugRVaGbWx51tpZSEKR/XmvawBSo0xHXQI3cvWEA/o/ZgyRPRfQiZ+4+zTLpr008FnkiD0nGzE0MVTllH1DdWSYhHiB+SPuQvHfBP5gVnG8Ri0583wQ6NkjhsF5G0Wwu7HsUw7XZiYZvfbZ/1lIg7cHCM7OocuceWOw2258p+ZbAJM6k02SMfqR61aNwpmzmhMv7lobgi16E4RBF9lrDVg9y46X5YTDvC2AC81AlkbERmAwMEYUvinWi0z+Kko7GKxQt9/UP6iwwP4jqiR/3Takoq6OdkMcm1kIXr1NFEt/vV+xzXK9yXrtOPmnnCMR+CcJ7xfx5HJ5D2JIdhwcg7Nta7ICitSiIrL3zzO3+owCUNETgajGkWuM1SgI9nPWJQwMxUCzrsa6M2SrAvw8TVnz/TLCXPvBYDiEKyXoTHg/C2LsL3VmtLH/6t0ZdzXxlv2iN1xiwK+IiF/OImbBvBw/UqXCQMdTyTeogpACy0JZznOMlXgd/nLRen721qzXvvq3/rh22USuHX0suHBW+K/OfcxUuEAKxxn4c+NhETDUtYAp4E5hHpqjR4hPaknwqY64t88K4Tbt5hp5Ggigj6yE="
  on:
    tags: true
    distributions: sdist bdist_wheel
    branch: master
    repo: drewpearce/legos.fact_sphere
